id: P001748
initial_creation_type: ocr
source_metadata:
  id: bdr:W22982
  title: ཀརྨ་བདུད་འཇོམས་ཞབས་ཀྱི་རྣམ་པར་ཐར་པ་གསལ་བྱེད་ཉིན་བྱེད་ངོ་མཚར་སྣང་བའི་གཏེར་མཛོད
  author: ''
  volumes:
    5189497fc8c14cc4aaeced2b85c8d4fc:
      image_group_id: I0884
      title: ''
      volume_number: 1
      total_pages: 386
