id: P001748
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:18:27.482891
source_metadata:
  id: bdr:W22982
  title: ཀརྨ་བདུད་འཇོམས་ཞབས་ཀྱི་རྣམ་པར་ཐར་པ་གསལ་བྱེད་ཉིན་བྱེད་ངོ་མཚར་སྣང་བའི་གཏེར་མཛོད
  author: ''
  volumes:
    5189497fc8c14cc4aaeced2b85c8d4fc:
      image_group_id: I0884
      title: ''
      volume_number: 1
      total_pages: 386
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
