id: IDC15ACB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:23:43+00:00'
last_modified: '2022-06-07T14:55:19.580088+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22982
  title: ཀརྨ་བདུད་འཇོམས་ཞབས་ཀྱི་རྣམ་པར་ཐར་པ་གསལ་བྱེད་ཉིན་བྱེད་ངོ་མཚར་སྣང་བའི་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    05B0:
      image_group_id: I0884
      title: ''
      total_pages: 386
      order: 1
      base_file: 05B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
